export default {
  /* Account
-------------------------------------------------------*/
  CLICK_SIGNIN_OR_UP: "CLICK_SIGNIN_OR_UP",
  INPUT_USERNAME: "INPUT_USERNAME",
  INPUT_PASSWORD: "INPUT_PASSWORD",
  INPUT_BUCKET: "INPUT_BUCKET",
  INPUT_BUCKETVAL: "INPUT_BUCKETVAL",
  REQUIRE_VERIFY_FORM: "REQUIRE_VERIFY_FORM",
  BREAK_VERIFY_FORM: "BREAK_VERIFY_FORM",
  REQUIRE_SIGNIN_OR_UP_FORM: "REQUIRE_SIGNIN_OR_UP_FORM",
  REQUEST_POST: "REQUEST_POST",

  /* Main
-------------------------------------------------------*/
  INITIATE: "INITIATE",
  CLICK_ROW: "CLICK_ROW",
  GET_NEW_STRUCTURE: "GET_NEW_STRUCTURE",
  PRINT_WORKING_DIRECTORY: "PRINT_WORKING_DIRECTORY",
  GET_FILE_CONTENT: "GET_FILE_CONTENT",
  CLEAR_CONTENT_VIEW: "CLEAR_CONTENT_VIEW",
  CLICK_DIRECTORY_RESOURCE: "CLICK_DIRECTORY_RESOURCE",
  REQUIRE_MKDIR_FORM: "REQUIRE_MKDIR_FORM",
  BREAK_MKDIR_FORM: "BREAK_MKDIR_FORM",
  MAKE_DIRECTORY: "MAKE_DIRECTORY",
  INPUT_DIRECTORY_NAME: "INPUT_DIRECTORY_NAME",
  CONTINUOUS_INPUT_MKDIR_FORM: "CONTINUOUS_INPUT_MKDIR_FORM",
  REDRAW_STRUCTURE: "REDRAW_STRUCTURE",
  CLICK_EXPAND: "CLICK_EXPAND",
  CLICK_REMOVE: "CLICK_REMOVE",
  CLICK_REMOVE_NEXT: "CLICK_REMOVE_NEXT",
  REQUIRE_REMOVE_MODAL: "REQUIRE_REMOVE_MODAL",
  REMOVE_RESOURCE: "REMOVE_RESOURCE",
  DID_REMOVE_RESOURCE: "DID_REMOVE_RESOURCE",
  BREAK_WORKING_RESOURCE: "BREAK_WORKING_RESOURCE",
  CLICK_EDIT: "CLICK_EDIT",
  CLICK_LOGOUT: "CLICK_LOGOUT",

  /* Modal
-------------------------------------------------------*/
  CLICK_CLOSE_MODAL: "CLICK_CLOSE_MODAL",
  CLICK_OPEN_MODAL_VERIFY: "CLICK_OPEN_MODAL_VERIFY",
  CLICK_OPEN_MODAL_MKDIR: "CLICK_OPEN_MODAL_MKDIR",
  CLICK_OPEN_MODAL_REMOVE: "CLICK_OPEN_MODAL_REMOVE"
};
